title: Mango's blog
author: mango
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  hellow world

# social links
twitter_username: ok
github_username:  ok

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
